server:
  port: 8888
spring:
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duynnapt/ecom-configure
          default-label: good_config
